### ISSUE TITLE
"product review" label gets deleted

### ISSUE THREAD

**Issue by nedbat** [openedx/openedx-webhooks#219]
(From a Slack discussion: https://openedx.slack.com/archives/C03R320AFJP/p1672944142897759 or 2U: https://twou.slack.com/archives/C03R320AFJP/p1672944142897759)

The bot has a set of labels intended to mirror Jira ticket statuses:
```
GITHUB_STATUS_LABELS = {
    "architecture review",
    "awaiting prioritization",
    "blocked by other work",
    "changes requested",
    "community manager review",
    "engineering review",
    "merged",
    "needs triage",
    "open edx community review",
    "product review",
    "rejected",
    "waiting on author",
}
```

When the bot can't find the status from Jira (as it can't now because the connection isn't re-established yet), it doesn't know the status, and so removes any of these labels.  When someone manually adds a label, the bot removes it during it's next pass over the pull request.

**Comment by nedbat** [comment]
The quick fix is to make the `GITHUB_STATUS_LABELS` set empty.  A more nuanced approach would be to leave those labels if we don't have a Jira connection.

@feanil

**Comment by feanil** [comment]
We ended up going with making the value an empty set.  via https://github.com/openedx/openedx-webhooks/pull/220

Making it work only if there are valid Jira settings seems like it would set us up for surprising future behavior if we ever do add Jira back.  Especially since we aren't sure that we want to be using labels to track Jira state like we used to.
